perwendel/spark

LICENSE
NOTICE

- Renamed LICENSE to NOTICE
- Added Apache 2 license as LICENSE
- Added notices from all bundled software

Fixed #233, Add top-level NOTICE file:

---

README.md

Hi all !
Im pretty new to Spark framework. When I was starting with it I have just copied examples from README and found out that there are a lot of unused imports. Whats more Spark claims that it looks really cool with Java 8 but examples are not fully showing power of Spark with Java 8. So I decided to create this small PR. 
Comments are welcome !

Update README: remove unused imports and add more Java 8 syntax

---

src/main/java/spark/servlet/FilterTools.java
src/main/java/spark/servlet/SparkFilter.java
src/main/java/spark/webserver/MatcherFilter.java

A tentative PR addressing issue https://github.com/perwendel/spark/issues/266

Make params/routes unicode strings

---

src/main/java/spark/SparkBase.java
src/main/java/spark/webserver/SparkServer.java

To be able to wait for the jetty server to be up before making requests. Fixes #226

added awaitInitialization method on SparkBase

---

src/main/java/spark/SparkBase.java
src/main/java/spark/utils/GzipUtils.java
src/main/java/spark/webserver/SparkServer.java

Fixing #222

---

src/main/java/spark/servlet/SparkApplication.java
src/main/java/spark/servlet/SparkFilter.java

I added the destroy() method to the SparkApplication interface with "default" modifier.

Added SparkApplication.destroy() Fixes #151 

---

.gitignore
pom.xml
src/main/java/spark/SparkBase.java
src/main/java/spark/webserver/SparkServer.java
src/main/java/spark/webserver/WebSocketCreatorFactory.java
src/test/java/spark/GenericIntegrationTest.java
src/test/java/spark/examples/websocket/EchoWebSocket.java
src/test/java/spark/examples/websocket/PingWebSocket.java
src/test/java/spark/examples/websocket/WebSocketExample.java
src/test/java/spark/webserver/WebSocketCreatorFactoryTest.java
src/test/java/spark/websocket/WebSocketTestClient.java
src/test/java/spark/websocket/WebSocketTestHandler.java

This PR is based on the comments in https://github.com/perwendel/spark/issues/196.
Adds basic support for WebSockets in the embedded server.

Added basic WebSocket support in the embedded server

---

src/test/java/spark/BodyAvailabilityTest.java
src/test/java/spark/GenericIntegrationTest.java
src/test/java/spark/GenericSecureIntegrationTest.java
src/test/java/spark/servlet/ServletTest.java

Hi Guys,
This PR contains a quick introduction how to easily improve your tests quality.
What about frameworks like AssertJ/Mockito/JUnitParams, do you consider those test dependencies at all? 
If so I have great candidates for this: `spark.RequestTest` and `spark.QueryParamsMapTest`

Reducing boilerplate code rethrowing exceptions in tests

---

src/main/java/spark/Request.java

Read body as string lazily on Request.java

Read body as string lazily

---

src/main/java/spark/Response.java

This is particularly useful for [preventing some XSS attacks](https://www.owasp.org/index.php/HttpOnly).

Add the ability to specify http only in a cookie

---

src/main/java/spark/servlet/SparkFilter.java
src/main/java/spark/staticfiles/StaticFiles.java
src/main/java/spark/utils/GzipUtils.java
src/main/java/spark/webserver/MatcherFilter.java
src/test/java/spark/GzipTest.java
src/test/java/spark/examples/gzip/GzipClient.java
src/test/java/spark/examples/gzip/GzipExample.java

Also added test cases for all gzip support and Gzip Example.

Added GZIP support for static files

---

pom.xml
src/test/java/spark/SparkInstanceTest.java

Adding test cases for SparkInstance.
Thanks!
Luis Jose Sztul Torselli

Add test cases for SparkInstance

---

src/test/java/spark/route/RouteEntryTest.java
src/test/java/spark/utils/MimeParseTest.java
src/test/java/spark/utils/SparkUtilsTest.java

Added test coverage for RouteEntry, MimeParse, and SparkUtils
Thanks!
Jett Gamboa

Added test coverage for RouteEntry, MimeParse, and SparkUtils

---

pom.xml
src/test/java/spark/RequestTest.java

Adding unit test coverage for spark.Request
Refactoring current tests for spark.Request to use Mockito
Thanks!
Jett Gamboa

Adding unit test coverage for spark.Request

---

pom.xml
src/test/java/spark/FilterImplTest.java
src/test/java/spark/RouteImplTest.java

Adding test cases for RouteImpl and FilterImpl.
Thanks!
Luis Jose Sztul Torselli

Added test cases for RouteImpl and FilterImpl

---

pom.xml
src/test/java/spark/ResponseTest.java

Adding test cases for Response.
Thanks!
Luis Jose Sztul Torselli

Add test cases for Response

---

README.md

Adding full unit test coverage for spark.Session
Adding Mockito and Powermock as dependencies in POM
Thanks!
Jett Gamboa

Added unit test coverage for spark.Session

---

.travis.yml
README.md
pom.xml

-  Add test cases for the methods StaticFiles.configureStaticResources and StaticFiles.configureExternalStaticResources
- Add test cases for the method ExceptionMapper.getInstance
- Add Mockito and Powermock to support the test cases added
Thanks!
Rodrigo Villalba

Add test cases for StaticFiles and ExceptionMapper

---

.travis.yml
README.md
pom.xml
src/main/java/spark/Spark.java

- Add test cases for the method StaticFiles.clear()
- Add test cases for the method SparkInstance.init()
- Add Mockito and Powermock to support the test cases added
Thanks!
Rodrigo Villalba.

Add test cases for StaticFiles and SparkInstance

---

src/main/java/spark/resource/AbstractResourceHandler.java
src/main/java/spark/resource/ClassPathResourceHandler.java

Removed jetty utils URIUtil references from resource handling classes (fixes #407)

---

src/main/java/spark/Request.java

This is very-very minor, so please merge ASAP.

 Error while generating apidocs #460.

---

src/main/java/spark/ResponseTransformerRouteImpl.java
src/main/java/spark/Service.java
src/main/java/spark/Spark.java
src/main/java/spark/TemplateViewRouteImpl.java
src/main/java/spark/embeddedserver/EmbeddedServerFactory.java
src/main/java/spark/embeddedserver/EmbeddedServers.java
src/main/java/spark/embeddedserver/jetty/EmbeddedJettyFactory.java
src/main/java/spark/http/matching/AfterFilters.java
src/main/java/spark/http/matching/BeforeFilters.java
src/main/java/spark/http/matching/MatcherFilter.java
src/main/java/spark/http/matching/RouteContext.java
src/main/java/spark/http/matching/Routes.java
src/main/java/spark/route/Routes.java
src/main/java/spark/route/ServletRoutes.java
src/main/java/spark/route/SimpleRouteMatcher.java
src/main/java/spark/servlet/SparkFilter.java
src/main/java/spark/staticfiles/StaticFiles.java
src/test/java/spark/MultipleServicesTest.java
src/test/java/spark/ServiceTest.java
src/test/java/spark/examples/multiple/MultipleServices.java
src/test/java/spark/route/RoutesTest.java
src/test/java/spark/staticfiles/StaticFilesTest.java

Planned use:
```java
igniteHelloService();
...
private static Service igniteHelloService() {
Service http = ignite()
.port(1234)
.staticFileLocation("/public")
.threadPool(40);
http.get("/hello", (q, a) -> "Hello World!");
http.get("/goodbye", (q, a) -> "Goodbye!");
http.redirect.any("/hi", "/hello");
return http;
}
```

For running multiple instances of Spark in one process.

---

src/test/java/spark/SessionTest.java
src/test/java/spark/embeddedserver/jetty/SocketConnectorFactoryTest.java
src/test/java/spark/embeddedserver/jetty/websocket/WebSocketCreatorFactoryTest.java
src/test/java/spark/embeddedserver/jetty/websocket/WebSocketServletContextHandlerFactoryTest.java
src/test/java/spark/utils/CollectionUtilsTest.java

- add generic type
- remove unused local variable

Fix test case

---

pom.xml

Refactor pom

---

src/main/java/spark/Response.java
src/test/java/spark/ResponseTest.java

add `Response#status()` and `Response#type()`

Fix for #503

---

src/main/java/spark/QueryParamsMap.java

I think the "p" (key regex pattern) variable should be a class variable.

Change to class variable

---

src/test/java/spark/resource/UriPathTest.java

Increased statement coverage for UriPath to >80%

Added unit tests for UriPath

---

src/test/java/spark/MultipleServicesTest.java
src/test/java/spark/examples/simple/SimpleSecureExample.java

Minor refactoring of SimpleSecureExample to make it clearer what to do.

Refactoring Secure Test

---

src/main/java/spark/Spark.java
src/test/java/spark/MultipleFiltersTest.java

Part of #555

---

src/main/java/spark/Service.java

Added @return to several methods, added  @param to one method.

Fix javadoc for Service.java

---

src/main/java/spark/http/matching/ResponseWrapper.java

see https://github.com/perwendel/spark/issues/599

Issue #559: Adds missing getters in ResponseWrapper

---

src/main/java/spark/Redirect.java

Fix javadoc, added @param for all methods

---

src/main/java/spark/ResponseTransformerRouteImpl.java

Route was not being passed through to the super method in RouteImpl and causing a null return when calling delegate.

Fixes #583

---

src/main/java/spark/servlet/SparkFilter.java
src/main/java/spark/utils/StringUtils.java

I have been working with the API and i think that it is great, i like keeping my code clean as much as possible and i think that a way to achieve it is that the end-points could be grouped into business modules. That's why i made some modifications in order to be able to support the configuration of multiple spark applications.

Support for multiple Spark applications in filter configuration

---

src/main/java/spark/Service.java
src/main/java/spark/Spark.java
src/main/java/spark/embeddedserver/EmbeddedServer.java
src/main/java/spark/embeddedserver/jetty/EmbeddedJettyServer.java
src/main/java/spark/embeddedserver/jetty/websocket/WebSocketCreatorFactory.java
src/main/java/spark/embeddedserver/jetty/websocket/WebSocketHandlerClassWrapper.java
src/main/java/spark/embeddedserver/jetty/websocket/WebSocketHandlerInstanceWrapper.java
src/main/java/spark/embeddedserver/jetty/websocket/WebSocketHandlerWrapper.java
src/main/java/spark/embeddedserver/jetty/websocket/WebSocketServletContextHandlerFactory.java
src/test/java/spark/ServiceTest.java
src/test/java/spark/embeddedserver/jetty/websocket/WebSocketCreatorFactoryTest.java
src/test/java/spark/embeddedserver/jetty/websocket/WebSocketServletContextHandlerFactoryTest.java

A new take on implementing feature request #367. A bit more complex than necessary, because I didn't want to change the internal workings (eg. time of handler class instantiation) too much.

Enable passing WebSocket handler instances.

---

src/main/java/spark/RouteImpl.java
src/main/java/spark/TemplateViewRouteImpl.java

fix issue 663

---

src/main/java/spark/embeddedserver/jetty/SocketConnectorFactory.java
src/test/java/spark/GenericIntegrationTest.java
src/test/java/spark/GenericSecureIntegrationTest.java

Fixes #320 
Courtesy of @t-kameyama

Fix for #320 - X-Forwarded-For support in request.ip()

---

src/main/java/spark/Routable.java
src/main/java/spark/Spark.java
src/test/java/spark/GenericIntegrationTest.java

Name change from 'done' do 'afterAfter' since 'done' is not really describing the functionality. We'd like to use 'finally' but it's a java keyword.

Rename from 'done' to 'afterAfter' (better name wanted)

---

.editorconfig

A very basic EditorConfig file (indent with 4 spaces).

---

README.md

Corrected out-of-date example code by replacing done(...) with afterAfter(...)

Corrected out-of-date example code

---

src/main/java/spark/Service.java
src/main/java/spark/Spark.java
src/main/java/spark/embeddedserver/jetty/SocketConnectorFactory.java
src/main/java/spark/ssl/SslStores.java

Address issue #562.  Just enables the jetty check to require client certificates.

added jetty check for client certificates

---

src/main/java/spark/staticfiles/MimeType.java

For these old school guys like me who like 3 letters extensions files.
Fixes issue #739.

Add mapping for ".htm" files

---

src/main/java/spark/embeddedserver/jetty/SocketConnectorFactory.java
src/main/java/spark/staticfiles/DirectoryTraversal.java
src/main/java/spark/staticfiles/MimeType.java
src/test/java/spark/GenericIntegrationTest.java
src/test/java/spark/StaticFilesFromArchiveTest.java
src/test/java/spark/StaticFilesMemberTest.java
src/test/java/spark/examples/simple/SimpleExample.java

remove all warnings

---

src/main/java/spark/Response.java
src/main/java/spark/http/matching/ResponseWrapper.java
src/test/java/spark/ResponseTest.java

Simple implementation for request #757 to add domain option to the cookie wrapper.

Added set-domain option for cookies

---

src/main/java/spark/embeddedserver/EmbeddedServers.java
src/main/java/spark/embeddedserver/jetty/EmbeddedJettyFactory.java
src/main/java/spark/embeddedserver/jetty/EmbeddedJettyServer.java
src/main/java/spark/embeddedserver/jetty/JettyServerFactory.java
src/test/java/spark/embeddedserver/EmbeddedServersTest.java

Fixes #796  #314
Adds an extension to let people configure their Jetty Server

Make Jetty servers tunable

---

src/main/java/spark/Response.java
src/main/java/spark/http/matching/ResponseWrapper.java
src/test/java/spark/CookiesIntegrationTest.java

See https://github.com/perwendel/spark/issues/780 for discussion regarding this pull request.

Cookies with path attribute can now be deleted

---

pom.xml
src/main/java/spark/embeddedserver/jetty/websocket/WebSocketServletContextHandlerFactory.java
src/test/java/spark/embeddedserver/jetty/websocket/WebSocketServletContextHandlerFactoryTest.java

Revert "Updated Jetty dependency and a test broken by Jetty changes."

---

pom.xml

Preparing for 2.6.0 release

---

src/main/java/spark/http/matching/Routes.java

don't do route.render if response is already redirected

---

src/main/java/spark/Request.java
src/test/java/spark/GenericIntegrationTest.java

Fix for https://github.com/perwendel/spark/issues/490

Fixed: plus signs in path params are parsed are they are

---

src/main/java/spark/Service.java

Resolves issue #920. Not sure if there are better suggestions on the exception message?

Add initialization check before blocking

---

README.md

I think it's good idea - add links for badges

Update readme - added links for badges

---

src/main/java/spark/embeddedserver/jetty/JettyServer.java
src/main/java/spark/resource/UriPath.java

Using findbugs found two inner if blocks explicitly always true or false

removed unreachable if conditions

---

pom.xml

This solves issue: #984 for me.

Update of pom.xml, updated jetty version

---

src/main/java/spark/http/matching/Body.java

Fixed documentation miskates

---

README.md

Changed the version number to 2.7.2

Update README.md with proper spark version

---

src/main/java/spark/ExceptionMapper.java
src/main/java/spark/Service.java
src/main/java/spark/embeddedserver/EmbeddedServerFactory.java
src/main/java/spark/embeddedserver/EmbeddedServers.java
src/main/java/spark/embeddedserver/jetty/EmbeddedJettyFactory.java
src/main/java/spark/http/matching/GeneralError.java
src/main/java/spark/http/matching/MatcherFilter.java
src/main/java/spark/servlet/SparkFilter.java
src/test/java/spark/ExceptionMapperTest.java
src/test/java/spark/embeddedserver/EmbeddedServersTest.java
src/test/java/spark/embeddedserver/jetty/EmbeddedJettyFactoryTest.java

First part of Issue #1010 blocks my development so I decided to fix it myself.
I'm new to spark code so let me know if I missed out something.

fixed service so each instance has its own instance of ExceptionMapper

---

pom.xml
src/test/java/spark/embeddedserver/jetty/JettyServerTest.java
src/test/webapp/WEB-INF/web.xml

P.S. I had to fix JettyServerTest because Jetty behaviour has been changed: now it throws IllegalArgumentException if `maxThreads` < `minThreads`.

upgrade dependencies

---

src/main/java/spark/RouteImpl.java

Quick little code improvement.

Remove redundant null check

---

src/main/java/spark/embeddedserver/jetty/SocketConnectorFactory.java

Remove call to deprecated (and empty) Jetty method

---

pom.xml

Bumped to latest stable Jetty version 9.4.15.v20190215

Bumped to latest stable Jetty version 9.4.15.v20190215

---

pom.xml

updated Spark version in pom.xml

prepare 2.9.0 release

---

pom.xml

Security fix in Jetty. Fix for #1117

Security fix in Jetty. Fix for #1117

---

pom.xml

Bumping version for 2.9.1 release

Bumping version for 2.9.1 release

---

pom.xml

Bumping to latest jetty version `9.4.30.v20200611`

Bumping to latest jetty version (9.4.30.v20200611)

---

pom.xml

Bumped to latest version of jetty. Functionality tested and verified.

Bumped Jetty version to latest

---

src/main/java/spark/Service.java
src/main/java/spark/embeddedserver/EmbeddedServer.java
src/main/java/spark/embeddedserver/jetty/EmbeddedJettyServer.java
src/main/java/spark/embeddedserver/jetty/websocket/WebSocketServletContextHandlerFactory.java
src/test/java/spark/embeddedserver/jetty/websocket/WebSocketServletContextHandlerFactoryTest.java

fix for #1146

---

.github/workflows/ci.yml

travis org stopped working & travis-ci.com not for free. Github actions for free.

Add build status
