src/main/java/spark/utils/IOUtils.java

I found that `mvn javadoc:javadoc` fails in master branch with the following environment.
* oracle-java8 (Java 1.8.0_40)
* Maven 3.0.5
* Ubuntu 15.04 beta
The cause of the error was an extra, obsolete param in a javadoc document, so I wrote a patch.

Remove obsolete param in a javadoc document

---

README.md
src/test/java/spark/examples/simple/SimpleExample.java
src/test/java/spark/examples/simple/SimpleSecureExample.java

Related to https://github.com/perwendel/spark/issues/243

Remove references to deprecated setPort method

---

src/main/java/spark/ResponseTransformerRouteImpl.java
src/main/java/spark/RouteImpl.java
src/main/java/spark/TemplateViewRouteImpl.java
src/main/java/spark/webserver/BytesSerializer.java
src/main/java/spark/webserver/DefaultSerializer.java
src/main/java/spark/webserver/InputStreamSerializer.java
src/main/java/spark/webserver/MatcherFilter.java
src/main/java/spark/webserver/Serializer.java
src/main/java/spark/webserver/SerializerChain.java
src/test/java/spark/GenericIntegrationTest.java

Adds Serializer interface for serializing output data to different formats instead of calling toString.
Before this PR the output was written to outputstream as a byte[] of a call to `toString` method. This works for almost all cases but if you want to return binary content (for example a dynamic generated pdf), then instead of writing the content of the pdf to output, it was written the result of calling `toString` method of a byte[] object which is totally wrong.
For this reason a Serializer abstract class has been created to implement a chain of responsibility pattern. Currently instead of calling `toString` method, Spark tries to resolve the output element. If it is a byte[] or ByteBuffer the output is written to output as is. If it is an InputStream then the inputstream is read and …

Adds Serializer class for serializing output data

---

src/main/java/spark/QueryParamsMap.java

by inserting missing double quotes

fix QueryParamsMap's javadoc

---

pom.xml

This supersedes pull request #121 (mine) which was conflicted. I resolved the conflict, but overly polluted the history, so here's a clean pull request.
This also supersedes pull request #164 (not mine) which had exactly the same changes and is now also conflicted.
As discussed previously, the only effect of this change is to add OSGi metadata into MANIFEST.MF, allowing the Spark jar to be seen as a bundle by any OSGi container. This change has absolutely no effect on anything other than the generated MANIFEST.MF file.

Add OSGi bundle configuration to pom so that Spark will build as a bundle.

---

pom.xml
src/main/java/spark/JettyLogger.java
src/main/java/spark/webserver/JettyHandler.java
src/main/java/spark/webserver/SparkServer.java
src/test/java/spark/RequestTest.java
src/test/java/spark/servlet/ServletTest.java

Update of jetty version from 9.0.2.v20130417 to 9.2.11.v20150529. This new version come with javax.servlet-api:3.1, better startup time, ThreadPool bugs fixed and other improvements that can be found here [Jetty 9.2.11 Roadmap](http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/tree/VERSION.txt?id=jetty-9.2.11.v20150529).
@perwendel Can you validate these changes please?

Jetty version 9.2.11.v20150529

---

src/main/java/spark/utils/GzipUtils.java

Long story short...  This patches a possible NPE when the Accept-Encoding header is empty.
On a simple Hello World server with ```get("/", (request, response) -> "Hello World");``` try the following:
curl http://localhost:4567  <=== works fine
curl -H "Accept-Encoding;" -v http://localhost:4567   <=== NPE
There were other ways to fix the error (check if there is even an accept encoding header available etc. ) but this was the easiest.

Add null check when Accept-Encoding header is empty.

---

src/main/java/spark/TemplateViewRoute.java

This restores the symmetry between the template operators and the other route types.

method `handle` of TemplateViewRoute can throw Exceptions

---

src/main/java/spark/Request.java
src/main/java/spark/webserver/RequestWrapper.java

This method supports URLs like:
http://host/resource?id=foo&id=bar
returning `request.getParamsValues("id")`as `["foo", "bar"]`
It simply delegates to the appropiate method in `HttpServletRequest`. Without it, the non-intuitive and a bit cumbersome way of getting this result is:
QueryParamsMap paramMap = request.queryMap("id");
if (paramMap.hasValue()) {
whatever(paramMap.values())
}

Add queryParamsValues to Request

---

src/main/java/spark/Request.java
src/main/java/spark/webserver/RequestWrapper.java
src/test/java/spark/examples/filter/FilterExampleAttributes.java

Improves the usability of the Request API, now that spark requires java 8.

Updated the Request object to enable type capture on the attribute(String) method.

---

src/main/java/spark/webserver/serialization/InputStreamSerializer.java

Hi Per,
This change copies a returned InputStream directly to output rather than read it in to memory first.  The InputStream might be large (making buffering a problem) and might not be valid UTF-8 (e.g. could be arbitrary data returned as application/octet-stream).

copy stream directly rather than buffer as a utf-8 string

---

src/main/java/spark/ExceptionHandler.java
src/main/java/spark/Filter.java
src/main/java/spark/ResponseTransformer.java
src/main/java/spark/Route.java
src/main/java/spark/TemplateViewRoute.java

The java annotation `@FunctionalInterface` is an informal annotation type,  to indicate that an interface type declaration is intended to be a functional interface as defined by the Java Language Specification.
With this annotation the compiler will throw an error, if this interface is changed in a way which would breaking existing Lambda usages etc.
Upon studying the Sparks API I was stumbling over compiler errors and was missing these annotations as a reassuring documentation.

Add @FunctionalInterface to Spark's functional interfaces in its API

---

src/main/java/spark/ExceptionMapper.java
src/main/java/spark/staticfiles/StaticFiles.java
src/test/java/spark/servlet/MyApp.java

This pull request is focused on resolving occurrences of Sonar rule squid:S2444 “Lazy initialization of static fields should be synchronized”. 
You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:S2444
Please let me know if you have any questions.
Faisal.

Code quality fix - Lazy initialization of static fields should be synchronized

---

src/main/java/spark/Request.java

Otherwise system default encoding is always used

Respect request encoding when parsing body

---

src/main/java/spark/Request.java
src/main/java/spark/Session.java
src/test/java/spark/GenericIntegrationTest.java
src/test/java/spark/RequestTest.java
src/test/java/spark/SessionTest.java

After invalidating a session, returns new session.
```
Session session = request.session();
session.invalidate();
session = request.session(); // get new sesssion
session.attribute("XXX", "YYY"); // don't throw exception
```
Add the `validSession` to conditions to get the new session in Request.

Fix for #251

---

src/main/java/spark/http/matching/MatcherFilter.java
src/main/java/spark/http/matching/Routes.java
src/main/java/spark/resource/AbstractResourceHandler.java
src/main/java/spark/resource/JarResourceHandler.java
src/main/java/spark/staticfiles/StaticFilesConfiguration.java

The ClassPathResourceHandler doesn't work when trying to access files in a jar. I've written a JarResourceHandler that does this. Should solve #535

Fix for #535. Static files in jar

---

src/main/java/spark/Spark.java

Halt methods should return HaltException instead of void to enable writing ```throw halt(401)```.
Currently in a route, one has to write ```halt(401); return null;```. The part ```return null;``` is useless and confusing since it will never be executed.

halt methods return HaltException instead of void

---

src/main/java/spark/http/matching/ResponseWrapper.java

this missing delegate causes a null pointer exception when using "public void cookie(String path, String name, String value, int maxAge, boolean secured, boolean httpOnly) "

added missing delegate implementation in ResponseWrapper

---

src/main/java/spark/staticfiles/MimeType.java

Hi,
As Spark will be guessing some mime types, would be nice to have web fonts mime types too.
Best regards.

Add web fonts mime types to MimeType inner map

---

src/main/java/spark/http/matching/ResponseWrapper.java
src/test/java/spark/ResponseWrapperDelegationTest.java

As I commented in PR [572](https://github.com/perwendel/spark/pull/572), there are other methods missing from the delegation, too.
I noticed the omission when writing an after-filter which tried to access response.status() and got an NPE. 
This PR adds the methods (and a test demonstrating the problem).

add missing delegate methods to ResponseWrapper

---

src/main/java/spark/resource/ExternalResource.java
src/test/java/spark/StaticFilesTest.java

The [mime type detection](https://github.com/perwendel/spark/blob/12774f1f20e2871c4dd19293d08dcf5afdd484db/src/main/java/spark/staticfiles/MimeType.java#L98) is based on the filename. This commit adds an implementation of `getFilename` for `ExternalResource` so the mime type is also set on external static files.

Implement getFilename for ExternalResource

---

src/main/java/spark/Service.java

The stop function cannot be ran in the same thread as the route handling thread so it has to be wrapped into another thread.
This ensures that no matter where you stop the server from it always shuts down gracefully.

Fixes #563

---

src/main/java/spark/Request.java
src/main/java/spark/http/matching/MatcherFilter.java
src/test/java/spark/GenericIntegrationTest.java

Adresses #528 #343 #267 #266  
Instead of taking the already decoded URI from jetty `httpRequest.getPathInfo()` we go back to the way it was done before [b621367](https://github.com/perwendel/spark/commit/b6213676146c3d78fa0b38870fa3b4ff1dedd7c0), using `httpRequest.getRequestURI()` and decode the parameters just before they are added to the params map instead. 
This solves the problem of matching routes using encoded slashes.

Postpone param/splat decoding until after matching.

---

src/main/java/spark/staticfiles/MimeType.java
src/main/java/spark/staticfiles/StaticFilesConfiguration.java

With Spark 2.5.1 automatic mime-type detection was introduced for static file system resources. If a static resources is being read from a jar, this mime-type detection was applied though. This pull request introduces the detection by inspecting the request pathinfo.

Fix mimetype setting for jar resources

---

src/main/java/spark/Request.java

Every request made to spark logs out "get splat" and "get params" which ironically is making debugging a bit more annoying when looking through a tailed log. They don't seem to add value so I've removed them.

Remove unecessary logging

---

src/main/java/spark/QueryParamsMap.java
src/test/java/spark/QueryParamsMapTest.java

I would like to add a hasKey (or containsKey if you like) method to QueryParamsMap. The use case is for a Boolean queryParam entry that has a default value. An example would be:
url/?describe
or
url/?describe=true
being equivalent.  Adding the method makes for cleaner code and removes the construction of a new map to call queryParamsMap.toMap().containsKey()

add hasKey method

---

src/main/java/spark/http/matching/MatcherFilter.java

If the route is rejected because of the Accept header, it's useful to know which one was used.
Also, changing to using SLF4J's parameter `{}` syntax.

log which accept header is not mapped

---

src/main/java/spark/Service.java
src/main/java/spark/TemplateViewRoute.java
src/main/java/spark/embeddedserver/EmbeddedServerFactory.java
src/main/java/spark/embeddedserver/EmbeddedServers.java
src/main/java/spark/embeddedserver/NotSupportedException.java
src/main/java/spark/http/matching/Halt.java
src/main/java/spark/http/matching/MatcherFilter.java
src/main/java/spark/route/HttpMethod.java
src/main/java/spark/route/SimpleRouteMatcher.java
src/main/java/spark/staticfiles/StaticFilesConfiguration.java

Javadoc modifications were made to following files, a summary of modifications:
Service.java
Fixed javadoc error "bad use of >". Enclosed -> in @literal
TemplateViewRoute.java
@throws added
EmbeddedServerFactory.java
@param added
@return added
EmbeddedServers.java
@param added
@return added
NotSupportedException.java
@param added
Halt.java
@param added
MatcherFilter.java
@param added
HttpMethod
@param added
@return added
StaticFilesConfiguration.java
Method description added
@param added
@throws added
SimpleRouteMatcher.java (this is a deprecated class. I added javadoc anyway to suppress maven warnings)
@param added
@return added

Fix javadoc error and warnings in several files

---

src/main/java/spark/staticfiles/DirectoryTraversal.java
src/main/java/spark/staticfiles/StaticFilesFolder.java

When Windows paths are received, like `C:\Users\USERNAME\AppData\Local\Temp\external\`, they will be changed to `C:/Users/USERNAME/AppData/Local/Temp/external`.

Make external static folder be *nix like

---

src/main/java/spark/embeddedserver/EmbeddedServer.java
src/main/java/spark/embeddedserver/jetty/EmbeddedJettyServer.java

Is there any interest to expose data like this?
Exposing this would allow monitoring the current server threads. I'd like to use that data to fine tune the server threads configuration.

Expose active server thread count

---

src/main/java/spark/staticfiles/StaticFilesConfiguration.java

Currently, the method `spark.staticfiles.StaticFiles.consume` leaves the file input stream open. In addition to being a bad idea in general, it also means that the server process has a file lock on all the static files all the time, which makes changing them on the fly (say using `gulp watch`) impossible. This PR fixes the issue by extracting the call to `resource.getInputStream()` into its own local variable, and explicitly closing the stream.

Close the static file input stream when done

---

src/test/java/spark/ServicePortIntegrationTest.java
src/test/java/spark/staticfiles/StaticFilesTest.java
src/test/java/spark/staticfiles/StaticFilesTestExternal.java

* Removed unused import that caused compiler warning
* Replaced use of deprecated URLEncoder.encode(String s) method with URLEncoder.encode(String s, String enc) alternative.

Made minor changes to avoid compiler warnings

---

src/main/java/spark/Service.java

When testing with `Spark`, it appeare that when we provide our webserver, not using jetty server emmbedded, `Spark`keep routes from a scenarii to another.
Now, i must done following thing in my unit test tear down method 😭  :
```
Class<?> sparkClass = Class.forName(Spark.class.getCanonicalName());
Method method = sparkClass.getDeclaredMethod("getInstance");
method.setAccessible(true);
Object sparkService = method.invoke(sparkClass);
//  Access to a protected field routes
Class<?> sparkInstanceClass = Class.forName("spark.Service");
Arrays.stream(sparkInstanceClass.getDeclaredFields())
.filter(f -> "routes".equals(f.getName()))
.findFirst()
.ifPresent(f -> {
// Access to the field routes and call clear() on it.
f.setAccessible(true);
try {
Routes routes  = (Routes) f.get(sparkService); …
```

Clear route on stop() properly

---

src/main/java/spark/RouteImpl.java

Same as factory methods of `ResponseTransformerRouteImpl`.
Otherwize you can't use the `Service#addRoute()` method

Make RouteImpl factory methods public

---

src/main/java/spark/ExceptionMapper.java
src/main/java/spark/Service.java

I have spend quite a lot of time debugging this "static state leak" when I experienced this between integration tests. I think it makes sense to treat mapped exception handlers analog to added routes once the server stops.

Clear ExceptionMapper mappings on stop, analog to clear routes

---

src/main/java/spark/ExceptionHandler.java
src/main/java/spark/ExceptionHandlerImpl.java
src/main/java/spark/Service.java
src/main/java/spark/Spark.java

Adding type information to the `ExceptionHandler`, so you do not have to cast the `Exception` to its subtype manually within the `handle` method.

Type info for ExceptionHandler

---

src/main/java/spark/Service.java
src/main/java/spark/Spark.java

As mentioned in issue [885](https://github.com/perwendel/spark/issues/885), the activeThreadCount was not accessible through the Spark class.
Created a method in Service and Spark classes to make it accessible.

Added activeThreadCount to Service and Spark classes

---

src/main/java/spark/Service.java
src/main/java/spark/staticfiles/StaticFilesConfiguration.java

Ditch local variables in `Service` in favour of consulting
the configuration object. Also fixes the issue of not properly
clearing on stop.

Use `StaticFilesConfiguration` as the single source of truth.

---

src/main/java/spark/embeddedserver/jetty/HttpRequestWrapper.java

large file uploads otherwise lead to out of memory error

disable http request wrapper byte cache for multipart/form-data uploads

---

src/main/java/spark/embeddedserver/jetty/EmbeddedJettyServer.java
src/main/java/spark/embeddedserver/jetty/SocketConnectorFactory.java

- To overcome Java IBM issues (handshake_failure) when deploying Spark
applications, the enabled protocols are now explicitly declared and set
on sslContextFactory during the creation of a Secure Socket Connector.
- This pull-request refers to Issue #914

Updating EmbeddedJettyServer to work with custom connectors 

---

src/main/java/spark/http/matching/MatcherFilter.java

This change makes it possible for external web containers to serve up the configured (or default) 404 response.

Enable custom 404 pages for external web container

---

pom.xml
src/main/java/spark/embeddedserver/jetty/EmbeddedJettyFactory.java
src/main/java/spark/embeddedserver/jetty/EmbeddedJettyServer.java
src/main/java/spark/embeddedserver/jetty/JettyServer.java
src/main/java/spark/embeddedserver/jetty/JettyServerFactory.java
src/test/java/spark/embeddedserver/EmbeddedServersTest.java
src/test/java/spark/embeddedserver/jetty/EmbeddedJettyFactoryTest.java
src/test/java/spark/embeddedserver/jetty/JettyServerTest.java

Nice to be able to override the default thread pool behaviour. One use case we had in mind was to be able to provide the Jetty embedded server a io.dropwizard.metrics InstrumentedQueuedThreadPool to provide better alerting and scaling via thread utilization in cloud deployments.

Added ability to pass ThreadPool to Jetty embedded server via factory

---

src/main/java/spark/Request.java
src/main/java/spark/utils/urldecoding/TypeUtil.java
src/main/java/spark/utils/urldecoding/UrlDecode.java
src/main/java/spark/utils/urldecoding/Utf8Appendable.java
src/main/java/spark/utils/urldecoding/Utf8StringBuilder.java

In 2.7.0 release a specific Jetty import was mistakenly added
in spark.Request. This PR fixes this.

Fixing #941 - Jetty specific import in spark.Request

---

src/main/java/spark/resource/ClassPathResourceHandler.java
src/main/java/spark/resource/ExternalResourceHandler.java
src/main/java/spark/staticfiles/DirectoryTraversal.java
src/main/java/spark/staticfiles/StaticFilesConfiguration.java
src/main/java/spark/staticfiles/StaticFilesFolder.java

Fixes issues #1031 and #1005 where multiple static file locations in different services would cause a DirectoryTraversal issue.

Each service has own static file location

---

src/main/java/spark/staticfiles/MimeType.java
src/test/java/spark/StaticFilesMemberTest.java
src/test/resources/public/js/module.mjs

Signed-off-by: Lawrence Ching <lawrence.ching.zh@gmail.com>
---
After the fix, Chrome now can load the module file and execute successfully.
And `.mjs` file is returned as `application/json`

#1093 Support .mjs file for MIME type auto detection

---

src/main/java/spark/QueryParamsMap.java

This fixes a few typos in the JavaDoc of QueryParamsMap.

fix typos in QueryParamsMap documentation

---

src/main/java/spark/Request.java
src/main/java/spark/http/matching/RequestWrapper.java
src/test/java/spark/RequestTest.java

PR for https://github.com/perwendel/spark/issues/1048 ping @perwendel

new field and getter in Request for matchedRoute

---

src/main/java/spark/Request.java
src/main/java/spark/http/matching/RequestWrapper.java
src/test/java/spark/RequestTest.java

Namechange from `matchedRouteUri` to `matchedPath` to better fit with current nomenclature.

Namechange from matchedRouteUri to matchedPath

---

pom.xml

This is part of a solution towards allowing Spark to serve cookies with the "SameSite" property.
Google Chrome 80, released in February 2020, is now treating the lack of a "SameSite" property in a cookie as equivalent to "SameSite: Lax", instead of "SameSite: None". This breaks functionality in some situations.
A fundamental problem for Java-based web apps is that the Servlet API doesn't yet support the "SameSite" cookie attribute.
Recent Jetty updates have added different workarounds to this problem. By updating the embedded Jetty to 9.4.27, these workarounds become available to Spark apps.

Updated embedded Jetty version to 9.4.27.v20200227

---

src/test/java/spark/BodyAvailabilityTest.java

This is a test refactoring
**Problem:**
The Magic Number Test occurs when assert() statements in a test method contain numeric literals (i.e., magic numbers) as parameters.
**Solution:**
As magic numbers do not indicate the meaning/purpose of the number, they should be replaced with constants or variables, thereby providing a descriptive name for the input.
_Before:_
`Assert.assertEquals(200, response.status);
`
_After:_
`Assert.assertEquals(HTTP_OK, response.status);`

Test improvement: removed Magic Number test smell

---

src/main/java/spark/serialization/InputStreamSerializer.java
src/test/java/spark/serialization/InputStreamSerializerTest.java

Alternative version of #978 , incorporating the feedback in that PR.
This makes the InputStreamSerializer responsible for closing the streams it is passed.  Also includes a couple of simple tests.

Ensure InputStreamSerializer closes its streams

---

src/main/java/spark/Service.java
src/test/java/spark/ServiceTest.java

Expose embeddeServerIdentifier, so that EmbeddedServers can be used to attach a different factory service to embedded Spark servers.

Expose get/set on Service.embeddedServerIdentifier

---

src/main/java/spark/Response.java
src/test/java/spark/ResponseTest.java

Useful for setting headers like `Expires` and `Last-Modified` that are
expected to contain timestamps.

Add methods to set long and date headers

---

src/main/java/spark/Service.java
src/main/java/spark/Spark.java
src/main/java/spark/route/Routes.java
src/main/java/spark/routematch/RouteMatch.java
src/test/java/spark/MultipleServicesTest.java
src/test/java/spark/RequestTest.java

I want to implement #1006. 
From what I understood, adding a `httpRequest` field to `RouteMatch `and exposing a `getRoutes` method in the `Service` and `Spark `classes.
A few lines were changed to accommodate the new field. 
And a new test in `MultipleServicesTest` to check if everything is dandy.

Get all mapped routes

---

src/main/java/spark/Base64.java

With Java 8 we can migrate to use `java.util.Base64.Decoder` / `Encoder` rather than  `sun.misc.BASE64Decoder` and `sun.misc.BASE64Encoder`.  
The  `sun.misc` classes are not be available in later versions of Java.

Modify Base64 to use java.util.Base64 Encoder/Decoder rather than the sun.misc classes

---

src/main/java/spark/Spark.java

Currently spark doesn't provide for a way to remove routes after they have already been registered. Several users on both StackOverflow and other forums asked how to access this functionality. My patch exposes two static methods in `spark.Spark`, one for removing a route based on the URL path, and another for removing a route based on the URL path and `HttpMethod`.
Removing routes at runtime could be useful if the developer wants to, for example, change the logic of a route at runtime, then redeploy. I personally use a forked and patched version of Spark with the ability to remove routes in maintaining a web-based API management system that lets users define logic through a web interface.

Add methods for removing routes at runtime

---

src/main/java/spark/Service.java
src/main/java/spark/Spark.java
src/main/java/spark/embeddedserver/EmbeddedServer.java
src/main/java/spark/embeddedserver/jetty/EmbeddedJettyServer.java
src/main/java/spark/embeddedserver/jetty/SocketConnectorFactory.java
src/test/java/spark/GenericSecureIntegrationTest.java
src/test/java/spark/embeddedserver/EmbeddedServersTest.java
src/test/java/spark/embeddedserver/jetty/EmbeddedJettyFactoryTest.java
src/test/java/spark/embeddedserver/jetty/SocketConnectorFactoryTest.java

It seems that from https://github.com/perwendel/spark/issues/320 Spark blindly trusts HTTP headers that can be spoofed, with no way to disable this behavior.
The newly introduced method ```Spark.trustForwardHeaders``` allows you to specify if you want to use jetty's ForwardedRequestCustomizer (https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/server/ForwardedRequestCustomizer.html)

added trustForwardHeaders method to decide if to trust HTTP forward headers
